### ISSUE TITLE
Bootstrap CSS not injected with gulp serve

### ISSUE THREAD

**Issue by sebcl** [Swiip/generator-gulp-angular#631]
Hello, I'm having almost the same issue somebody [had some time ago](https://github.com/Swiip/generator-gulp-angular/issues/67), in which Bootstrap is not being injected in my index.html. I'm using plain css, no precompiler, and plain everything. It used to work just fine, but at some point a few days ago, I can't `serve` anymore.

This is happening in an actual project I'm working on, but I can't show it publicly so I created a new project and got the same issue (haven't touched any file in the folder).

**Program versions:**
```
$ gulp -v
[16:00:33] CLI version 3.9.0
[16:00:33] Local version 3.8.11

$ node -v
v0.12.4

$ yo --version
1.4.7

$ npm list | grep generator-gulp-angular
├── generator-gulp-angular@0.12.1 extraneous
```

You can also [check my screenshot](https://s3.amazonaws.com/f.cl.ly/items/0W0i3K011d3T3L2M0X1K/Captura%20de%20pantalla%202015-06-23%20a%20las%2015.57.03.jpg)

**Comment by Swiip** [comment]
The fix was about puting an override block in the bower.json, do you see it ?

**Comment by zckrs** [comment]
I just trying. Everything work.

Can you check your `bower.json` ? And can you paste your `.yo-rc.json` here ?

**Comment by sebcl** [comment]
Hi, here they are:

**.yo-rc.json**
```json
{
  "generator-gulp-angular": {
    "version": "0.11.0",
    "props": {
      "angularVersion": "~1.3.4",
      "angularModules": [],
      "jQuery": {
        "key": "jquery2"
      },
      "resource": {
        "key": "restangular",
        "module": "restangular"
      },
      "router": {
        "key": "angular-route",
        "module": "ngRoute"
      },
      "ui": {
        "key": "bootstrap",
        "module": null,
        "name": "bootstrap"
      },
      "bootstrapComponents": {
        "key": "official",
        "module": null
      },
      "cssPreprocessor": {
        "key": "none",
        "extension": "css"
      },
      "jsPreprocessor": {
        "key": "none",
        "extension": "js",
        "srcExtension": "js"
      },
      "htmlPreprocessor": {
        "key": "none",
        "extension": "html"
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      }
    }
  }
}
```

**bower.json**
```json
{
  "name": "we",
  "version": "0.0.0",
  "dependencies": {
    "jquery": "~2.1.1",
    "restangular": "~1.4.0",
    "angular-route": "~1.3.4",
    "bootstrap": "~3.3.1",
    "angular": "~1.3.4"
  },
  "devDependencies": {
    "angular-mocks": "~1.3.4"
  },
  "resolutions": {
    "jquery": "~2.1.1",
    "angular": "~1.3.4"
  }
}
```

**Comment by sebcl** [comment]
@Swiip I have no "styles.js" file in my gulp folder, or anything containing `sassOptions` in any file on the project folder.

**Comment by sebcl** [comment]
I just tried on a Windows machine where I had my project **untouched** and it works fine.

But I tried a fresh `npm install && bower install` in ANOTHER folder and **it doesn't work**! It behaves the same than what I just showed here.

**Comment by sebcl** [comment]
FOUND THE PROBLEM!!!!

Turns out **bootstrap 3.3.5 is screwed up!!**

Not sure what the problem is, really, you will  understand it better than me i guess. The problem is that bower.json requires ~3.3.1 which means if they screw up in a minor patch, the entire project dies, like what happened here. So I changed it to explicitly 3.3.4 (for now at least) and reran `bower install`. Now it works again.

**Comment by sebcl** [comment]
Found the problem. Turns out minor release of bootstrap (3.3.5) doesn't play nice with inject, so I changed the bower.json file to explicitly use 3.3.4.

@Swiip @zckrs  I think the generator should use exact dependency versions. As we all learned with this, minor updates can screw things up and even render an entire project unfunctional. I'll send a pull request for this change.

**Comment by Swiip** [comment]
We'll not take a PR with all versions fixed. We already debate on the mater. Between those who wants always the last version et those who wants stability, there is no perfect solution.

We have to look into your point and find what've changed in bootstrap 3.3.5 and find a new solution.

**Comment by Swiip** [comment]
Ok, I just gave a quick look at the bootstrap repo. It's exactly on the 3.3.5 release that they have changed their bower.json. The one we fixed in the 0.12.1. Did you well regenerate your project since you update to the 0.12.1 of the generator?

By the way, I see that they also have removed the font links in the bower file which will cause us other troubles.

**Comment by zckrs** [comment]
```
Hi, here they are:

.yo-rc.json

{
  "generator-gulp-angular": {
    "version": "0.11.0",
    "props": {
```

You should rerun `yo gulp-angular`. You use a old version of generator.

**Comment by sebcl** [comment]
What exactly do you mean? The problem happened with a brand new project I created for my test too. I ended up forcing bootstrap to 3.3.4 and it solved. 

I really think there should be an choice in the generator between Stability or risky-youCouldLoseYourJob versions.

**Comment by zckrs** [comment]
Fixed by https://github.com/Swiip/generator-gulp-angular/pull/662

**Comment by zckrs** [comment]
v1.0.0-rc1 released on NPM.

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)

**Comment by timelyxyz** [comment]
The same issue exists in bootstrap 3.3.6 =(

**Comment by SunEagle** [comment]
It's still not clear for me how I can solve this problem.
My project builds the same way as sebfindling's screenshot.
Can someone please explain me with details?
