### ISSUE TITLE
Fonts Aren't Copied to Dist - Works on OSX But Not Linux Server

### ISSUE THREAD

**Issue by iamchairs** [Swiip/generator-gulp-angular#644]
Not sure how to give the best information for this but the fonts files aren't being copied to the dist/fonts/ directory on my linux server. It is working fine on my OSX dev machine however.

OSX Output:

```
gulp build
[18:09:10] Using gulpfile xxx/gulpfile.js
[18:09:10] Starting 'scripts'...
[18:09:10] Starting 'styles'...
[18:09:11] Starting 'partials'...
[18:09:11] Starting 'fonts'...
[18:09:11] Starting 'other'...
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
[18:09:12] gulp-inject 45 files into index.less.
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
[18:09:14] Finished 'styles' after 3.49 s
[18:09:15] Finished 'fonts' after 3.77 s
[18:09:15] Time: 2182ms
   Asset   Size  Chunks             Chunk Names
index.js  68614       0  [emitted]  main
[18:09:15] Finished 'scripts' after 4.81 s
[18:09:15] Starting 'inject'...
[18:09:15] gulp-inject 1 files into index.html.
[18:09:15] gulp-inject 1 files into index.html.
[18:09:15] Finished 'inject' after 25 ms
[18:09:15] Finished 'partials' after 4.11 s
[18:09:15] Starting 'html'...
[18:09:15] gulp-inject 1 files into index.html.
[18:09:32] Finished 'other' after 21 s
[18:09:32] 'dist/' styles/app-bcef3035.css 53.9 kB
[18:09:32] 'dist/' scripts/app-a03cbc3f.js 48 kB
[18:09:32] 'dist/' styles/vendor-66762bbe.css 112.98 kB
[18:09:32] 'dist/' scripts/vendor-1d69d702.js 558.15 kB
[18:09:32] 'dist/' index.html 666 B
[18:09:32] 'dist/' all files 773.7 kB
[18:09:32] Finished 'html' after 17 s
[18:09:32] Starting 'build'...
[18:09:32] Finished 'build' after 11 μs
```

Linux Output:

```
gulp build
[23:08:02] Using gulpfile xxx/gulpfile.js
[23:08:02] Starting 'scripts'...
[23:08:03] Starting 'styles'...
[23:08:03] Starting 'partials'...
[23:08:03] Starting 'fonts'...
[23:08:04] Starting 'other'...
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
[23:08:07] gulp-inject 45 files into index.less.
[23:08:08] Finished 'fonts' after 4.12 s
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
[23:08:10] Finished 'styles' after 7.19 s
[23:08:13] Time: 6055ms
   Asset   Size  Chunks             Chunk Names
index.js  68614       0  [emitted]  main
[23:08:13] Finished 'scripts' after 11 s
[23:08:13] Starting 'inject'...
[23:08:13] gulp-inject 1 files into index.html.
[23:08:13] gulp-inject 1 files into index.html.
[23:08:13] Finished 'inject' after 49 ms
[23:08:13] Finished 'other' after 9.93 s
[23:08:13] Finished 'partials' after 10 s
[23:08:13] Starting 'html'...
[23:08:14] gulp-inject 1 files into index.html.
[23:08:44] 'dist/' styles/app-23ae5ead.css 54.48 kB
[23:08:44] 'dist/' styles/vendor-474244d3.css 118.12 kB
[23:08:44] 'dist/' scripts/app-7a22d7ec.js 48 kB
[23:08:44] 'dist/' scripts/vendor-f19aae87.js 568.87 kB
[23:08:44] 'dist/' index.html 666 B
[23:08:44] 'dist/' all files 790.13 kB
[23:08:44] Finished 'html' after 30 s
[23:08:44] Starting 'build'...
[23:08:44] Finished 'build' after 37 μs
```

In the end. OSX has a `dist/fonts/` directory and Linux doesn't.

**Comment by zckrs** [comment]
You use a old version of generator

**Comment by iamchairs** [comment]
How do I update after I used the generator?

**Comment by zckrs** [comment]
This post should help you http://stackoverflow.com/questions/18480316/how-to-upgrade-existing-project-scaffolded-with-yeoman

**Comment by iamchairs** [comment]
Updated the generator version to `^0.12.1` and reran the generator. Then ran npm install.

Font's still didn't transfer on Linux.

Do I need to run bleeding edge?

**Comment by Swiip** [comment]
Dups #637

**Comment by isaacweathers** [comment]
Just tried after updating with latest. Looks like it is having some issues on serve:dist copying the font files from bower to dist. The fonts folder is never created even though the task runs.
.js
[21:37:21] Starting 'scripts'...
[21:37:21] Starting 'styles'...
[21:37:21] Starting 'partials'...
[21:37:21] Starting 'fonts'...
[21:37:21] Starting 'other'...
[21:37:22] gulp-inject 2 files into index.less.
[21:37:23] Finished 'styles' after 2.27 s
[21:37:23] all files 7.9 kB
[21:37:23] Finished 'scripts' after 2.49 s
[21:37:23] Starting 'inject'...
[21:37:24] Finished 'partials' after 2.39 s
[21:37:24] gulp-inject 1 files into index.html.
[21:37:24] Finished 'fonts' after 2.31 s
[21:37:24] gulp-inject 10 files into index.html.
[21:37:24] Finished 'inject' after 443 ms
[21:37:24] Starting 'html'...
[21:37:24] gulp-inject 1 files into index.html.
[21:37:24] Finished 'other' after 2.77 s
[21:37:41] 'dist/' styles/app-4159cf83d7.css 118.44 kB
[21:37:41] 'dist/' styles/vendor-389eb5336b.css 58.61 kB
[21:37:41] 'dist/' scripts/app-066df6fa26.js 6.29 kB
[21:37:41] 'dist/' scripts/vendor-649835bb53.js 459.85 kB
[21:37:41] 'dist/' index.html 640 B
[21:37:41] 'dist/' all files 643.82 kB
[21:37:41] Finished 'html' after 18 s
[21:37:41] Starting 'build'...
[21:37:41] Finished 'build' after 13 μs
[21:37:41] Starting 'serve:dist'...
[21:37:41] Finished 'serve:dist' after 51 ms
[BS] [BrowserSync SPA] Running...
[BS] Access URLs:
 --------------------------------

**Comment by iomgi** [comment]
I have the same issue on OSX with the 0.12.1 version of the generator.
No fonts folder present in the dist folder.
Fresh project, no errors in the console output.

**Comment by Swiip** [comment]
It's because bootstrap stoped linking fonts in their bower configuration file. It's fixed in the PR #662

**Comment by antoescu** [comment]
I have the same problem and I see that it is already fixed, but how do you fix it when you already have a project running? (With custom gulp tasks, different directories, etc). Thanks

**Comment by Swiip** [comment]
In your `bower.json`, add:
```json
"overrides": {
  "bootstrap": {
    "main": [
      "dist/fonts/glyphicons-halflings-regular.eot",
      "dist/fonts/glyphicons-halflings-regular.svg",
      "dist/fonts/glyphicons-halflings-regular.ttf",
      "dist/fonts/glyphicons-halflings-regular.woff",
      "dist/fonts/glyphicons-halflings-regular.woff2"
    ]
  }
}
```

**Comment by antoescu** [comment]
Hi, thanks for the quick response. I still cannot see the /fonts folder in my dist.

Here is the bower.js

 {
  "name": "myapp",
  "version": "0.0.0",
  "dependencies": {
    "jquery": "~2.1.4",
    "angular-ui-router": "~0.2.15",
    "bootstrap-sass-official": "~3.3.4",
    "animate.css": "~3.3.0",
    "angular": "~1.4.0",
    "angular-localization": "~1.2.1",
    "flag-icon-css": "~0.7.1",
    "angularjs-slider": "~0.1.21",
    "ng-file-upload": "~5.0.9",
    "angular-ui-sortable": "~0.13.4"
  },
  "devDependencies": {
    "angular-mocks": "~1.4.0"
  },
  "resolutions": {
    "jquery": "~2.1.4",
    "angular": "~1.4.0"
  },
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/fonts/glyphicons-halflings-regular.eot",
        "dist/fonts/glyphicons-halflings-regular.svg",
        "dist/fonts/glyphicons-halflings-regular.ttf",
        "dist/fonts/glyphicons-halflings-regular.woff",
        "dist/fonts/glyphicons-halflings-regular.woff2"
      ]
    }
  }
}

Let me know if I am doing something wrong. Thanks!

**Comment by Swiip** [comment]
In your case, it's `bootstrap-sass-official` in place of `bootstrap` in the overrides

**Comment by antoescu** [comment]
Thanks again. Unfortunately this still doesn't work, I don't see a fonts folder in dist and also adds a new problem. In my index.scss, the part where boostrap should be added between // bower:scc and // endbower doesn't get added if I add what you just mentioned. I am getting kind of crazy trying different stuff. Let me know if you come with another idea. Thanks

**Comment by scttcper** [comment]
I'm missing fonts in dist folder as well on a new project started from current master. Running gulp serve:dist doesn't work either.

Using .pipe($.replace('../../bower_components/bootstrap-sass-official/assets/fonts/bootstrap/', '../fonts/')) and copying the fonts and not doing a gulp clean works for now.
